/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Pelanggan;

import Transaksi.Cetak_Transaksi;
import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.Statement;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import koneksi.koneksi;

/**
 *
 * @author fahim
 */
public class lihat_pesanan extends javax.swing.JFrame {
    String idTransaksi = "";
    private javax.swing.ButtonGroup bgStatus;
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(lihat_pesanan.class.getName());

    /**
     * Creates new form lihat_pesanan
     */
    public lihat_pesanan() {
        initComponents();
        tampilData();
        warnaStatus();
        bgStatus = new javax.swing.ButtonGroup();
        bgStatus.add(jRadioButton1);
        bgStatus.add(jRadioButton2);
        setSize(850,600);
        
        
        }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jButton1 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jRadioButton1 = new javax.swing.JRadioButton();
        jRadioButton2 = new javax.swing.JRadioButton();
        jButton2 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Daftar Pesanan Pelanggan");

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable1MouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTable1);

        jButton1.setText("Konfirmasi Pesanan");
        jButton1.addActionListener(this::jButton1ActionPerformed);

        jLabel2.setText("Status");

        jRadioButton1.setText("Lunas");

        jRadioButton2.setText("Pending");

        jButton2.setText("< Kembali");
        jButton2.addActionListener(this::jButton2ActionPerformed);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 751, Short.MAX_VALUE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jRadioButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jRadioButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jButton1)))
                        .addContainerGap())
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jButton2)
                        .addGap(215, 215, 215)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(18, 18, 18))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jButton2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel2)
                        .addComponent(jRadioButton1)
                        .addComponent(jRadioButton2))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 236, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jButton1)))
                .addContainerGap(126, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTable1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1MouseClicked
        // TODO add your handling code here:
        int baris = jTable1.getSelectedRow();
        if (baris == -1) return;

        // Ambil ID Transaksi untuk keperluan update status
        idTransaksi = jTable1.getValueAt(baris, 0).toString();
        bgStatus.clearSelection(); //
    
        // Ambil status dari kolom indeks 5 untuk menyalakan radio button
        String status = jTable1.getValueAt(baris, 5).toString();
        if (status.equalsIgnoreCase("Lunas")) {
            jRadioButton1.setSelected(true); //
        } else {
            jRadioButton2.setSelected(true); //
        }
    }//GEN-LAST:event_jTable1MouseClicked

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        try {
        if (idTransaksi.equals("")) {
            JOptionPane.showMessageDialog(null, "Pilih data terlebih dahulu");
            return;
        }

        String status = "";
        String sql = "";
        int uangTunai = 0;
        int uangKembalian = 0;
        String jenisPesanan = "";

        if (jRadioButton1.isSelected()) {
            status = "Lunas";
            sql = "UPDATE transaksi SET status_pembayaran=?, lunas_transaksi=NOW() WHERE id_transaksi=?";
            
            int totalHarga = 0;
            Connection connCheck = koneksi.getConnection();
            String sqlCheck = "SELECT total_harga, jenis_pesanan FROM transaksi WHERE id_transaksi = ?";
            java.sql.PreparedStatement pstCheck = connCheck.prepareStatement(sqlCheck);
            pstCheck.setString(1, idTransaksi);
            java.sql.ResultSet rsCheck = pstCheck.executeQuery();
            if (rsCheck.next()) {
                totalHarga = rsCheck.getInt("total_harga");
                jenisPesanan = rsCheck.getString("jenis_pesanan");
            }
            
            String inputTunai = JOptionPane.showInputDialog(this, "Total Belanja: Rp " + totalHarga + "\nMasukkan Uang Tunai Pelanggan:");
            if (inputTunai == null) return;
            
            try {
                uangTunai = Integer.parseInt(inputTunai.trim());
                if (uangTunai < totalHarga) {
                    JOptionPane.showMessageDialog(this, "Uang tunai kurang! Ubah status gagal.");
                    return;
                }
            } catch (NumberFormatException e) {
                JOptionPane.showMessageDialog(this, "Input harus berupa angka!");
                return;
            }
            uangKembalian = uangTunai - totalHarga;
            
        } else if (jRadioButton2.isSelected()) {
            status = "Pending";
            sql = "UPDATE transaksi SET status_pembayaran=?, lunas_transaksi=NULL WHERE id_transaksi=?";
        } else {
            JOptionPane.showMessageDialog(null, "Pilih status pembayaran (Lunas / Pending) terlebih dahulu!");
            return;
        }

        Connection conn = koneksi.getConnection();
        java.sql.PreparedStatement pst = conn.prepareStatement(sql);

        pst.setString(1, status);
        pst.setString(2, idTransaksi);
        pst.executeUpdate();

        JOptionPane.showMessageDialog(null, "Status berhasil diubah & Waktu Pembayaran dicatat!");
        tampilData();
        
        if (status.equals("Lunas")) {
            Cetak_Transaksi cetak = new Cetak_Transaksi(idTransaksi, uangTunai, uangKembalian, jenisPesanan);
            cetak.setVisible(true);
        }

    } catch (Exception e) {
        JOptionPane.showMessageDialog(null, e.getMessage());
    }
    
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        new pelanggan_pesan().setVisible(true);
        dispose();
    }//GEN-LAST:event_jButton2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new lihat_pesanan().setVisible(true));
    }
    
    private void tampilData() {
    DefaultTableModel model = new DefaultTableModel();
    model.addColumn("ID Transaksi");     // Indeks 0 (Wajib ID Transaksi agar oper data sukses)
    model.addColumn("Nama Pelanggan");   // Indeks 1
    model.addColumn("No Meja");         // Indeks 2
    model.addColumn("Menu");             // Indeks 3
    model.addColumn("Total Harga");      // Indeks 4
    model.addColumn("Status Pembayaran");// Indeks 5
    model.addColumn("Tanggal Transaksi");// Indeks 6

    try {
        Connection conn = koneksi.getConnection();

        // Ambil t.id_transaksi di bagian awal SELECT
        String sql = "SELECT "
                + "t.id_transaksi, "
                + "p.nama_pelanggan, "
                + "t.no_meja, "
                + "GROUP_CONCAT(d.nama_menu SEPARATOR ', ') AS item_dibeli, "
                + "t.total_harga, "
                + "t.status_pembayaran, "
                + "t.tanggal_transaksi "
                + "FROM transaksi t "
                + "INNER JOIN pelanggan p ON t.id_pelanggan = p.id_pelanggan "
                + "INNER JOIN detail_transaksi d ON t.id_transaksi = d.id_transaksi "
                + "GROUP BY t.id_transaksi";

        Statement st = conn.createStatement();
        ResultSet rs = st.executeQuery(sql);

        while (rs.next()) {
            model.addRow(new Object[]{
                rs.getInt("id_transaksi"),
                rs.getString("nama_pelanggan"),
                rs.getString("no_meja"),
                rs.getString("item_dibeli"),
                rs.getInt("total_harga"),
                rs.getString("status_pembayaran"),
                rs.getDate("tanggal_transaksi")
            });
        }

        jTable1.setModel(model);
        warnaStatus();

    } catch (Exception e) {
        JOptionPane.showMessageDialog(null, "Gagal Menampilkan Data : " + e.getMessage());
    }
}
    
    private void warnaStatus() {
    jTable1.setDefaultRenderer(Object.class, new javax.swing.table.DefaultTableCellRenderer() {
        private final javax.swing.JTextArea textArea = new javax.swing.JTextArea();

        {
            textArea.setLineWrap(true);       // Mengaktifkan bungkus teks otomatis
            textArea.setWrapStyleWord(true);  // Bungkus teks berdasarkan keutuhan kata (tidak terpotong di tengah huruf)
            textArea.setOpaque(true);
            textArea.setBorder(javax.swing.BorderFactory.createEmptyBorder(5, 5, 5, 5)); // Memberi jarak/padding biar rapi
        }

        @Override
        public java.awt.Component getTableCellRendererComponent(
                javax.swing.JTable table, Object value, boolean isSelected,
                boolean hasFocus, int row, int column) {

            // Set teks ke JTextArea renderer
            textArea.setText(value != null ? value.toString() : "");

            // Mengatur font agar sama dengan font tabel bawaan
            textArea.setFont(table.getFont());

            // PENGATURAN WARNA SELEKSI
            if (isSelected) {
                textArea.setBackground(table.getSelectionBackground());
                textArea.setForeground(table.getSelectionForeground());
            } else {
                textArea.setForeground(table.getForeground());
                
                // PENGATURAN WARNA STATUS (Menggunakan indeks kolom 5)
                if (row < table.getRowCount() && table.getColumnCount() > 5) {
                    Object statusObj = table.getValueAt(row, 5);
                    String status = (statusObj != null) ? statusObj.toString() : "";

                    if (status.equalsIgnoreCase("Pending")) {
                        textArea.setBackground(java.awt.Color.ORANGE);
                    } else {
                        textArea.setBackground(java.awt.Color.WHITE);
                    }
                } else {
                    textArea.setBackground(table.getBackground());
                }
            }

            // Menghitung tinggi ideal baris berdasarkan panjang teks yang dibungkus
            int columnWidth = table.getColumnModel().getColumn(column).getWidth();
            textArea.setSize(columnWidth, 1); // Set lebar komponen saat ini
            int preferredHeight = textArea.getPreferredSize().height;
            
            // Jika tinggi ideal lebih besar dari tinggi baris tabel sekarang, naikkan tinggi barisnya
            if (table.getRowHeight(row) != preferredHeight) {
                table.setRowHeight(row, Math.max(preferredHeight, 40)); // Minimal tinggi baris 35
            }

            return textArea;
        }
    });
}

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JRadioButton jRadioButton1;
    private javax.swing.JRadioButton jRadioButton2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    // End of variables declaration//GEN-END:variables
}
