/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Pelanggan;

/**
 *
 * @author fahim
 */
import Dashboard.Dashboard;
import java.sql.Connection;
import java.sql.PreparedStatement;
import javax.swing.JOptionPane;
import koneksi.koneksi;
import java.sql.Statement;
import java.sql.ResultSet;
import javax.swing.table.DefaultTableModel;

public class pelanggan_pesan extends javax.swing.JFrame {
    String JK;
    
    DefaultTableModel modelKeranjang = new DefaultTableModel();
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(pelanggan_pesan.class.getName());

    /**
     * Creates new form pelanggan_pesan
     */
    public pelanggan_pesan() {
        initComponents();
        java.util.Date tanggalSekarang = new java.util.Date();
        jDateChooser1.setDate(tanggalSekarang);
        jDateChooser1.setEnabled(false);
        
        jComboBox1.addActionListener(new java.awt.event.ActionListener() {
        @Override
        public void actionPerformed(java.awt.event.ActionEvent evt) {
            String kategoriDipilih = jComboBox1.getSelectedItem().toString();
            tampilkanData(kategoriDipilih); 
        }
    });
        modelKeranjang.addColumn("ID Menu");
        modelKeranjang.addColumn("Nama Menu");
        modelKeranjang.addColumn("Harga");
        modelKeranjang.addColumn("Jumlah");
        
        // Ganti 'jTable2' dengan nama variabel JTable kanan Anda yang asli
        jTable2.setModel(modelKeranjang);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jComboBox1 = new javax.swing.JComboBox<>();
        jTextField1 = new javax.swing.JTextField();
        jTextField2 = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable2 = new javax.swing.JTable();
        jLabel5 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jDateChooser1 = new com.toedter.calendar.JDateChooser();
        jButton5 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        txtQty = new javax.swing.JSpinner();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Menu Pesanan Pelanggan (Kasir)");

        jLabel2.setText("Pilih Kategori : ");

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable1MouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTable1);

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Makanan", "Minuman" }));
        jComboBox1.setSelectedIndex(-1);
        jComboBox1.addActionListener(this::jComboBox1ActionPerformed);

        jLabel3.setText("Nama             :");

        jLabel4.setText("No Meja         :");

        jTable2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane2.setViewportView(jTable2);

        jLabel5.setText("Jumlah : ");

        jButton1.setBackground(new java.awt.Color(51, 102, 255));
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setText("🛒 Keranjang");
        jButton1.addActionListener(this::jButton1ActionPerformed);

        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);

        jButton2.setText("🖋️ Edit");
        jButton2.addActionListener(this::jButton2ActionPerformed);

        jButton3.setText("🗑️ Hapus");
        jButton3.addActionListener(this::jButton3ActionPerformed);

        jButton4.setBackground(new java.awt.Color(51, 255, 51));
        jButton4.setText("✅ Konfirmasi Pesanan");
        jButton4.addActionListener(this::jButton4ActionPerformed);

        jButton5.setText("Lihat Pesananan");
        jButton5.addActionListener(this::jButton5ActionPerformed);

        jButton6.setText("< Dashboard");
        jButton6.addActionListener(this::jButton6ActionPerformed);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 503, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 452, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 185, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jButton4)))
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButton5)
                        .addGap(18, 18, 18)
                        .addComponent(jDateChooser1, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(36, 36, 36)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(20, 20, 20)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 269, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, 269, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(39, 39, 39)
                                        .addComponent(jLabel5)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(txtQty, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jButton2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jButton3))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, 269, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE)))))
                .addGap(18, 18, 18))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jButton6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 199, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(358, 358, 358))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addComponent(jButton6))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jDateChooser1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton5))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2)
                    .addComponent(jLabel5)
                    .addComponent(jButton2)
                    .addComponent(jButton3)
                    .addComponent(txtQty, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 220, Short.MAX_VALUE)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(16, 16, 16)
                        .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(240, 240, 240))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTable1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_jTable1MouseClicked

    private void jComboBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox1ActionPerformed
        // TODO add your handling code here:
        if(jComboBox1.getSelectedIndex()==0){
            JK="Makanan";
        } else {
            JK="Minuman";
        }
    }//GEN-LAST:event_jComboBox1ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        int barisDipilih = jTable1.getSelectedRow();
    if (barisDipilih == -1) {
        JOptionPane.showMessageDialog(this, "Silakan pilih menu terlebih dahulu di tabel kiri!");
        return;
    }
    
    // 2. Validasi & Ambil nilai Qty dari JTextField txtQty
    int qtyInput = 0;
    try {
        String qtyTeks = txtQty.getValue().toString().trim();
        if (qtyTeks.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Masukkan jumlah terlebih dahulu!");
            return;
        }
        qtyInput = Integer.parseInt(qtyTeks);
        
        // Validasi jika user memasukkan angka 0 atau minus
        if (qtyInput <= 0) {
            JOptionPane.showMessageDialog(this, "Jumlah harus lebih dari 0!");
            return;
        }
    } catch (NumberFormatException e) {
        JOptionPane.showMessageDialog(this, "Jumlah harus berupa angka!");
        return;
    }
    
    // 3. Ambil data dari tabel kiri
    String idMenu = jTable1.getValueAt(barisDipilih, 0).toString();
    String namaMenu = jTable1.getValueAt(barisDipilih, 1).toString();
    int hargaSatuan = Integer.parseInt(jTable1.getValueAt(barisDipilih, 3).toString());
    
    // 4. Hitung Subtotal untuk item ini (Harga x Qty Input)
    int subTotalItem = hargaSatuan * qtyInput;
    
    // 5. Cek apakah menu ini sudah ada di tabel kanan (keranjang preview)
    boolean sudahAda = false;
    int indeksBarisAda = -1;
    
    for (int i = 0; i < jTable2.getRowCount(); i++) {
        if (jTable2.getValueAt(i, 0).toString().equals(idMenu)) {
            sudahAda = true;
            indeksBarisAda = i;
            break;
        }
    }
    
    // 6. Masukkan atau update data di tabel kanan
    if (sudahAda) {
        // Jika sudah ada, akumulasikan Qty lama dengan Qty baru
        int qtyLama = Integer.parseInt(jTable2.getValueAt(indeksBarisAda, 3).toString());
        int qtyTotalBaru = qtyLama + qtyInput;
        
        // Update kolom Qty (indeks 3)
        jTable2.setValueAt(qtyTotalBaru, indeksBarisAda, 3);
    } else {
        // Jika belum ada, masukkan data baru (ID, Nama, Harga Satuan, Qty Input)
        modelKeranjang.addRow(new Object[]{idMenu, namaMenu, hargaSatuan, qtyInput});
    }
    
    // 7. Hitung ulang total keseluruhan di bawah
    hitungTotal();
    
    // 8. RESET form Qty menjadi kosong kembali setelah sukses input
    txtQty.setValue("");
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        int barisDipilih = jTable2.getSelectedRow();
    
    // 2. Validasi jika user belum memilih baris yang mau dihapus
    if (barisDipilih == -1) {
        JOptionPane.showMessageDialog(this, "Silakan pilih item di tabel kanan yang ingin dihapus!");
        return;
    }
    
    // 3. Konfirmasi sebelum menghapus (opsional, biar lebih aman)
    int konfirmasi = JOptionPane.showConfirmDialog(this, 
            "Apakah Anda yakin ingin menghapus menu ini dari keranjang?", 
            "Konfirmasi Hapus", JOptionPane.YES_NO_OPTION);
            
    if (konfirmasi == JOptionPane.YES_OPTION) {
        // 4. Hapus baris dari MODEL tabel kanan
        modelKeranjang.removeRow(barisDipilih);
        
        // 5. Hitung ulang total semua harga setelah ada yang dihapus
        hitungTotal();
        
        }
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        int barisDipilih = jTable2.getSelectedRow();
    
    // 2. Validasi jika user belum memilih baris
    if (barisDipilih == -1) {
        JOptionPane.showMessageDialog(this, "Silakan pilih item di tabel kanan yang ingin diedit!");
        return;
    }
    
    // 3. Ambil Qty lama sebagai nilai awal di kotak input
    String qtyLama = jTable2.getValueAt(barisDipilih, 3).toString();
    
    // 4. Munculkan pop-up input untuk memasukkan Qty baru
    String inputQtyBaru = JOptionPane.showInputDialog(this, "Masukkan Jumlah baru:", qtyLama);
    
    // Jika user menekan tombol 'Cancel' atau menyilangkan pop-up
    if (inputQtyBaru == null) {
        return; 
    }
    try {
        int qtyBaru = Integer.parseInt(inputQtyBaru.trim());
        
        if (qtyBaru <= 0) {
            JOptionPane.showMessageDialog(this, "Qty harus lebih besar dari 0! Gunakan tombol hapus jika ingin membatalkan.");
            return;
        }
        
        // 6. Update nilai Qty baru ke kolom indeks ke-3 pada tabel kanan
        jTable2.setValueAt(qtyBaru, barisDipilih, 3);
        
        // 7. Hitung ulang total semua harga
        hitungTotal();
        
    } catch (NumberFormatException e) {
        JOptionPane.showMessageDialog(this, "Input harus berupa angka!");
    }
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
        // 1. AMBIL INPUT DARI KASIR & VALIDASI
    String namaPelanggan = jTextField1.getText().trim(); 
    String noMeja = jTextField2.getText().trim();       
    int jumlahBarisKeranjang = jTable2.getRowCount(); // Tabel kanan (keranjang)
    
    if (namaPelanggan.isEmpty()) {
        JOptionPane.showMessageDialog(this, "Nama pelanggan harus diisi!");
        return;
    }
    if (noMeja.isEmpty()) {
        JOptionPane.showMessageDialog(this, "Nomor meja harus diisi!");
        return;
    }
    if (jumlahBarisKeranjang == 0) {
        JOptionPane.showMessageDialog(this, "Keranjang belanja masih kosong!");
        return;
    }
    
    // 2. AMBIL TANGGAL DARI JDATECHOOSER
    if (jDateChooser1.getDate() == null) {
        JOptionPane.showMessageDialog(this, "Tanggal transaksi tidak valid!");
        return;
    }
    java.util.Date dateFromChooser = jDateChooser1.getDate();
    java.sql.Date sqlDate = new java.sql.Date(dateFromChooser.getTime());
    
    // 3. HITUNG TOTAL HARGA KESELURUHAN DARI KERANJANG
    int totalHargaSemua = 0;
    for (int i = 0; i < jumlahBarisKeranjang; i++) {
        int harga = Integer.parseInt(jTable2.getValueAt(i, 2).toString());
        int qty = Integer.parseInt(jTable2.getValueAt(i, 3).toString());
        totalHargaSemua += (harga * qty);
    }
    
    Connection conn = null;
    try {
        conn = koneksi.getConnection();
        conn.setAutoCommit(false); // Transaksi manual agar aman (roll back jika ada yang gagal)
        
        // =========================================================================
        // PROSES A: INSERT NAMA PELANGGAN & AMBIL ID AUTO INCREMENT-NYA
        // =========================================================================
        String sqlPelanggan = "INSERT INTO pelanggan (nama_pelanggan) VALUES (?)";
        PreparedStatement psPelanggan = conn.prepareStatement(sqlPelanggan, java.sql.Statement.RETURN_GENERATED_KEYS);
        psPelanggan.setString(1, namaPelanggan);
        psPelanggan.executeUpdate();
        
        int idPelangganOtomatis = 0;
        ResultSet rsKeyPelanggan = psPelanggan.getGeneratedKeys();
        if (rsKeyPelanggan.next()) {
            idPelangganOtomatis = rsKeyPelanggan.getInt(1);
        }
        
        // =========================================================================
        // PROSES B: INSERT UTAMA KE tabel_transaksi (id_transaksi KOSONG / AUTO_INCREMENT)
        // =========================================================================
        // Perhatikan query: id_transaksi tidak ditulis agar MySQL mengisinya sendiri otomatis.
        String sqlTransaksi = "INSERT INTO transaksi (id_pelanggan, no_meja, tanggal_transaksi, total_harga, status_pembayaran) VALUES (?, ?, ?, ?, 'Pending')";
        
        // Wajib menambahkan Statement.RETURN_GENERATED_KEYS agar Java bisa menangkap id_transaksi otomatisnya
        PreparedStatement psTrx = conn.prepareStatement(sqlTransaksi, java.sql.Statement.RETURN_GENERATED_KEYS);
        psTrx.setInt(1, idPelangganOtomatis);
        psTrx.setString(2, noMeja);
        psTrx.setDate(3, sqlDate); 
        psTrx.setInt(4, totalHargaSemua);
        psTrx.executeUpdate();
        
        // Tangkap id_transaksi berupa angka INT hasil Auto Increment dari database
        int idTransaksiOtomatis = 0;
        ResultSet rsKeyTrx = psTrx.getGeneratedKeys();
        if (rsKeyTrx.next()) {
            idTransaksiOtomatis = rsKeyTrx.getInt(1); // Ini akan menghasilkan angka urut 1, 2, 3, dst.
        }
        
        // =========================================================================
        // PROSES C: INSERT ITEM KE DETAIL TRANSAKSI & POTONG STOK DI TABEL MENU
        // =========================================================================
        String sqlDetail = "INSERT INTO detail_transaksi (id_transaksi, id_menu, nama_menu, harga, jumlah) VALUES (?, ?, ?, ?, ?)";
        PreparedStatement psDetail = conn.prepareStatement(sqlDetail);
        
        String sqlUpdateStok = "UPDATE menu SET stok = stok - ? WHERE id_menu = ?";
        PreparedStatement psUpdateStok = conn.prepareStatement(sqlUpdateStok);
        
        for (int i = 0; i < jumlahBarisKeranjang; i++) {
            String idMenu = jTable2.getValueAt(i, 0).toString();
            int qtyBeli = Integer.parseInt(jTable2.getValueAt(i, 3).toString());
            
            // Atur parameter detail transaksi (Menggunakan setInt untuk ID Transaksi)
            psDetail.setInt(1, idTransaksiOtomatis); // Memasukkan ID angka yang tadi ditangkap
            psDetail.setString(2, idMenu);
            psDetail.setString(3, jTable2.getValueAt(i, 1).toString());
            psDetail.setInt(4, Integer.parseInt(jTable2.getValueAt(i, 2).toString()));
            psDetail.setInt(5, qtyBeli);
            psDetail.addBatch();
            
            // Atur parameter potong stok menu
            psUpdateStok.setInt(1, qtyBeli);
            psUpdateStok.setString(2, idMenu);
            psUpdateStok.addBatch();
        }
        
        // Eksekusi semua antrean batch secara bersamaan
        psDetail.executeBatch();
        psUpdateStok.executeBatch();
        
        // JIKA SEMUA BERHASIL, SIMPAN PERMANEN KE DATABASE
        conn.commit();
        
        JOptionPane.showMessageDialog(this, "Pesanan Berhasil Disimpan!\n"
                + "ID Transaksi: " + idTransaksiOtomatis + " (Otomatis)\n"
                + "Nama Pelanggan: " + namaPelanggan + " (ID: " + idPelangganOtomatis + ")\n"
                + "No Meja: " + noMeja + "\n"
                + "Status: Pending");
        
        // 4. RESET FORM & BERSIHKAN TAMPILAN KERANJANG
        jTextField1.setText("");
        jTextField2.setText("");
        if (txtQty != null) txtQty.setValue(0);
        
        DefaultTableModel model = (DefaultTableModel) jTable2.getModel();
        model.setRowCount(0);
        jLabel6.setText("Total: Rp 0");
        
        new lihat_pesanan().setVisible(true);
        dispose();
        
    } catch (Exception e) {
        // Jika ada proses yang gagal, batalkan semuanya agar data tidak timpang/corrupt
        if (conn != null) {
            try { conn.rollback(); } catch (Exception ex) { ex.printStackTrace(); }
        }
        JOptionPane.showMessageDialog(this, "Gagal memproses transaksi: " + e.getMessage(), "Database Error", JOptionPane.ERROR_MESSAGE);
    }
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        // TODO add your handling code here:
        new lihat_pesanan().setVisible(true);
        dispose();
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        // TODO add your handling code here:
        new Dashboard().setVisible(true);
        dispose();
    }//GEN-LAST:event_jButton6ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new pelanggan_pesan().setVisible(true));
    }
    private void tampilkanData(String kategori) {
    // 1. Definisikan kolom JTable Anda
    DefaultTableModel model = new DefaultTableModel();
    model.addColumn("ID Menu");
    model.addColumn("Nama Menu");
    model.addColumn("Kategori");
    model.addColumn("Harga");
    model.addColumn("Stok");
    
    try {
        // 2. Buat koneksi ke database (sesuaikan dengan kelas koneksi Anda)
        Connection conn = koneksi.getConnection(); 
        
        // 3. Buat Query SQL dengan parameter WHERE
        String query = "SELECT * FROM menu WHERE kategori = ?";
        PreparedStatement ps = conn.prepareStatement(query);
        ps.setString(1, kategori); // Mengisi tanda tanya (?) dengan parameter kategori
        
        ResultSet rs = ps.executeQuery();
        
        // 4. Looping hasil query dan masukkan ke dalam model tabel
        while (rs.next()) {
            model.addRow(new Object[]{
                rs.getString("id_menu"),
                rs.getString("nama_menu"),
                rs.getString("kategori"),
                rs.getInt("harga"),
                rs.getInt("stok")
            });
        }
        
        // 5. Set model baru ke JTable Anda (misal namanya tabelMenu)
        jTable1.setModel(model);
        
    } catch (Exception e) {
        JOptionPane.showMessageDialog(this, "Gagal mengambil data: " + e.getMessage());
    }
}
    private void hitungTotal() {
    int totalSemua = 0;
    int jumlahBaris = jTable2.getRowCount();
    
    for (int i = 0; i < jumlahBaris; i++) {
        int harga = Integer.parseInt(jTable2.getValueAt(i, 2).toString());
        int qty = Integer.parseInt(jTable2.getValueAt(i, 3).toString());
        
        // Menjumlahkan total keseluruhan (Harga Satuan * Qty)
        totalSemua += (harga * qty);
    }
    
    // Set hasil akhir ke label total transaksi di bawah tabel preview
    jLabel6.setText("Total: Rp " + totalSemua);
}

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JComboBox<String> jComboBox1;
    private com.toedter.calendar.JDateChooser jDateChooser1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTable1;
    private javax.swing.JTable jTable2;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JSpinner txtQty;
    // End of variables declaration//GEN-END:variables
}
