/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Transaksi;

import Pelanggan.lihat_pesanan;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import koneksi.koneksi;

/**
 *
 * @author fahim
 */
public class Cetak_Transaksi extends javax.swing.JFrame {
    private String idTransaksiTerpilih = "";
    private int tunaiDiterima = 0;
    private int kembalianDiterima = 0;
    private String jenisPesananDiterima = "";
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(Cetak_Transaksi.class.getName());

    /**
     * Creates new form Lihat_Transaksi
     */
    public Cetak_Transaksi() {
        initComponents();
    }
    
    public Cetak_Transaksi(String idTrx, int tunai, int kembalian, String jenisPesanan) {
        initComponents();
        this.idTransaksiTerpilih = idTrx;
        this.tunaiDiterima = tunai;
        this.kembalianDiterima = kembalian;
        this.jenisPesananDiterima = jenisPesanan;

        setLocationRelativeTo(null);
        tampilkanDetailDanInfo();
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        jLabel1.setText("Detail Transaksi");

        jLabel2.setText("ID Transaksi : ");

        jLabel3.setText("Nama Pelanggan : ");

        jLabel4.setText("Nomor Meja : ");

        jLabel5.setText("Tanggal Bayar : ");

        jButton1.setText("Cetak");
        jButton1.addActionListener(this::jButton1ActionPerformed);

        jButton2.setText("< Kembali");
        jButton2.addActionListener(this::jButton2ActionPerformed);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jButton2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel1)
                        .addGap(336, 336, 336))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 746, Short.MAX_VALUE)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel2)
                                    .addComponent(jLabel3)
                                    .addComponent(jLabel4)
                                    .addComponent(jLabel5)
                                    .addComponent(jButton1))
                                .addGap(0, 0, Short.MAX_VALUE)))
                        .addContainerGap())))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(25, 25, 25))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jButton2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)))
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel5)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 348, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton1)
                .addContainerGap(116, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        cetakStrukKeLog();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        new lihat_pesanan().setVisible(true);
        dispose();
    }//GEN-LAST:event_jButton2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new Cetak_Transaksi().setVisible(true));
    }
    
private void tampilkanDetailDanInfo() {
    // QUERY TAMPILKAN INFO MASTER PELANGGAN KE LABEL
    String sqlMaster = "SELECT t.id_transaksi, p.nama_pelanggan, t.no_meja, t.tanggal_transaksi "
                     + "FROM transaksi t "
                     + "INNER JOIN pelanggan p ON t.id_pelanggan = p.id_pelanggan "
                     + "WHERE t.id_transaksi = ?";
    try {
        java.sql.Connection conn = koneksi.getConnection();
        java.sql.PreparedStatement pstMaster = conn.prepareStatement(sqlMaster);
        pstMaster.setString(1, idTransaksiTerpilih);
        java.sql.ResultSet rsMaster = pstMaster.executeQuery();
        
        if (rsMaster.next()) {
            jLabel2.setText("ID Transaksi : " + rsMaster.getInt("id_transaksi"));
            jLabel3.setText("Nama Pelanggan : " + rsMaster.getString("nama_pelanggan"));
            jLabel4.setText("Nomor Meja : " + rsMaster.getString("no_meja"));
            jLabel5.setText("Tanggal Bayar : " + rsMaster.getDate("tanggal_transaksi"));
        }
    } catch (Exception e) {
        System.out.println("Gagal memuat info master: " + e.getMessage());
    }

    // PENGISIAN JTABLE DETAIL MENU
    DefaultTableModel model = new DefaultTableModel();
    model.addColumn("No");
    model.addColumn("Nama Menu");
    model.addColumn("Harga Satuan");
    model.addColumn("Jumlah Beli");
    model.addColumn("Subtotal");

    String sqlDetail = "SELECT d.nama_menu, d.harga, d.jumlah, (d.harga * d.jumlah) AS subtotal "
                     + "FROM detail_transaksi d "
                     + "WHERE d.id_transaksi = ?";
                     
    try {
        java.sql.Connection conn = koneksi.getConnection();
        java.sql.PreparedStatement pst = conn.prepareStatement(sqlDetail);
        pst.setString(1, idTransaksiTerpilih);
        java.sql.ResultSet rs = pst.executeQuery();

        int no = 1;
        while (rs.next()) {
            model.addRow(new Object[]{
                no++,
                rs.getString("nama_menu"),
                rs.getInt("harga"),
                rs.getInt("jumlah"),
                rs.getInt("subtotal")
            });
        }
        
        jTable1.setModel(model);
        jTable1.setRowHeight(25); 

    } catch (Exception e) {
        JOptionPane.showMessageDialog(this, "Gagal memuat detail transaksi: " + e.getMessage());
    }
}
    
private void cetakStrukKeLog() {
    if (idTransaksiTerpilih.equals("")) {
        JOptionPane.showMessageDialog(this, "Tidak ada data transaksi yang dapat dicetak!");
        return;
    }

    javax.swing.JTextArea areaStruk = new javax.swing.JTextArea();
    StringBuilder struk = new StringBuilder();
    
    String sqlMaster = "SELECT t.id_transaksi, p.nama_pelanggan, t.no_meja, t.tanggal_transaksi, "
                     + "t.total_harga, t.status_pembayaran, t.lunas_transaksi, t.jenis_pesanan "
                     + "FROM transaksi t "
                     + "INNER JOIN pelanggan p ON t.id_pelanggan = p.id_pelanggan "
                     + "WHERE t.id_transaksi = ?";
                     
    try {
        java.sql.Connection conn = koneksi.getConnection();
        java.sql.PreparedStatement pst = conn.prepareStatement(sqlMaster);
        pst.setString(1, idTransaksiTerpilih);
        java.sql.ResultSet rs = pst.executeQuery();
        
        if (rs.next()) {
            java.sql.Timestamp waktuLunas = rs.getTimestamp("lunas_transaksi");
            String formatJamSelesai = "-";
            if (waktuLunas != null) {
                java.text.SimpleDateFormat sdf = new java.text.SimpleDateFormat("dd-MM-yyyy HH:mm:ss");
                formatJamSelesai = sdf.format(waktuLunas);
            }

            String tipePesanan = rs.getString("jenis_pesanan");
            if (tipePesanan == null || tipePesanan.equals("")) {
                tipePesanan = jenisPesananDiterima;
            }

            struk.append("========================================\n");
            struk.append("                 RESTOGATE              \n");
            struk.append("         Jl. Mangga No 46, Jakarta      \n");
            struk.append("             Telp. 089677239028         \n");
            struk.append("========================================\n");
            struk.append("ID Transaksi : ").append(rs.getInt("id_transaksi")).append("\n");
            struk.append("Pelanggan    : ").append(rs.getString("nama_pelanggan")).append("\n");
            struk.append("No Meja      : ").append(rs.getString("no_meja")).append("\n");
            struk.append("Jenis        : ").append(tipePesanan).append("\n");
            struk.append("\n");
            struk.append("Kasir        : ").append(koneksi.namaKasirLogin).append("\n");
            struk.append("").append(formatJamSelesai).append("\n");
            struk.append("========================================\n");
            
            int jumlahBaris = jTable1.getRowCount(); 
            for (int i = 0; i < jumlahBaris; i++) {
                String namaMenu = jTable1.getValueAt(i, 1).toString();   
                String hargaSatuan = jTable1.getValueAt(i, 2).toString(); 
                String qtyBeli = jTable1.getValueAt(i, 3).toString();    
                String subTotal = jTable1.getValueAt(i, 4).toString();   
                
                struk.append(" ").append(namaMenu).append("\n");
                struk.append("   ").append(qtyBeli).append(" x Rp ").append(hargaSatuan)
                     .append("\t            Rp ").append(subTotal).append("\n");
            }
            
            struk.append("========================================\n");
            struk.append("TOTAL BELANJA : \t    Rp ").append(rs.getInt("total_harga")).append("\n");
            struk.append("TUNAI         : \t    Rp ").append(tunaiDiterima).append("\n");
            struk.append("KEMBALIAN     : \t    Rp ").append(kembalianDiterima).append("\n");
            struk.append("STATUS        : \t    ").append(rs.getString("status_pembayaran").toUpperCase()).append("\n");
            struk.append("========================================\n");
            struk.append("       Terima Kasih Atas Kunjungan      \n");
            struk.append("                  Anda!                 \n");
            struk.append("========================================\n");
            
            areaStruk.setText(struk.toString());
            areaStruk.setFont(new java.awt.Font("Courier New", java.awt.Font.PLAIN, 10)); 
            
            String pathFolder = "C:\\RestoGatePayment\\Struk Pelanggan\\";
            String namaFilePDF = "struk_transaksi_" + idTransaksiTerpilih + ".pdf";
            
            java.io.File folder = new java.io.File(pathFolder);
            if (!folder.exists()) {
                folder.mkdirs(); 
            }
            
            java.awt.print.PrinterJob job = java.awt.print.PrinterJob.getPrinterJob();
            javax.print.PrintService[] services = javax.print.PrintServiceLookup.lookupPrintServices(null, null);
            javax.print.PrintService pdfService = null;
            
            for (javax.print.PrintService service : services) {
                if (service.getName().toLowerCase().contains("pdf")) {
                    pdfService = service;
                    break;
                }
            }
            
            if (pdfService != null) {
                job.setPrintService(pdfService);
                
                javax.print.attribute.PrintRequestAttributeSet attr = new javax.print.attribute.HashPrintRequestAttributeSet();
                String urlPath = "file:/" + pathFolder.replace("\\", "/") + namaFilePDF;
                urlPath = urlPath.replace(" ", "%20"); 

                attr.add(new javax.print.attribute.standard.Destination(new java.net.URI(urlPath)));
                
                java.awt.print.PageFormat pf = job.defaultPage();
                pf.setOrientation(java.awt.print.PageFormat.PORTRAIT);
                
                java.awt.print.Paper paper = new java.awt.print.Paper();
                double width = 595;  
                double height = 842; 
                paper.setSize(width, height);
                paper.setImageableArea(36, 36, width - 72, height - 72); 
                pf.setPaper(paper);
                
                final java.awt.print.Printable originalPrintable = areaStruk.getPrintable(null, null);
                
                job.setPrintable(new java.awt.print.Printable() {
                    @Override
                    public int print(java.awt.Graphics graphics, java.awt.print.PageFormat pageFormat, int pageIndex) throws java.awt.print.PrinterException {
                        if (pageIndex > 0) {
                            return java.awt.print.Printable.NO_SUCH_PAGE;
                        }
                        java.awt.Graphics2D g2d = (java.awt.Graphics2D) graphics;
                        g2d.translate(pageFormat.getImageableX(), pageFormat.getImageableY());
                        
                        double scaleX = pageFormat.getImageableWidth() / 240.0; 
                        g2d.scale(scaleX, scaleX); 
                        
                        g2d.translate(-pageFormat.getImageableX(), -pageFormat.getImageableY());
                        return originalPrintable.print(g2d, pageFormat, pageIndex);
                    }
                }, pf);
                
                job.print(attr);
                JOptionPane.showMessageDialog(this, "Struk PDF A4 Berhasil Dibuat Secara Otomatis!\nTersimpan di: " + pathFolder + namaFilePDF);
            } else {
                boolean complete = areaStruk.print(null, null, false, null, null, true);
                if (complete) {
                    JOptionPane.showMessageDialog(this, "Struk PDF sukses dicetak!");
                }
            }
        } else {
            JOptionPane.showMessageDialog(this, "Data transaksi tidak ditemukan di database!");
        }
    } catch (Exception e) {
        JOptionPane.showMessageDialog(this, "Gagal memproses cetak otomatis ke folder: " + e.getMessage());
    }
}

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    // End of variables declaration//GEN-END:variables
}
